title: Home
icon: mdi:home
path: home
panel: true
cards:
  # Better layout control
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
            # #################################
            # Big text to display - Greeting
            # #################################
          - type: markdown
            content: >
              #
              {% if now().hour < 10 %}
              Good morning.
              {% elif now().hour > 18 %}
              Good evening.
              {% else %}
              Good day.
              {% endif %}
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 20px;
                  margin-top: 5px;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 20px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
          - type: markdown
            content: >
                #
                {% if is_state('device_tracker.sarah', 'home') and  is_state('device_tracker.pieter', 'home')%}
                Pieter and Sarah are home.
                {% elif not is_state('device_tracker.sarah', 'home') and  is_state('device_tracker.pieter', 'home')%}
                Pieter is home.
                {% elif is_state('device_tracker.sarah', 'home') and  not is_state('device_tracker.pieter', 'home')%}
                Sarah is home.
                {% else %}
                No one is home.
                {% endif %}
                {% if is_state('binary_sensor.back_door_sensor', 'on') and is_state('binary_sensor.front_door_sensor', 'on')%}
                The front door and the back door are open.
                {% elif not is_state('binary_sensor.back_door_sensor', 'on') and is_state('binary_sensor.front_door_sensor', 'on')%}
                The front door is open.
                {% elif is_state('binary_sensor.back_door_sensor', 'on') and not is_state('binary_sensor.front_door_sensor', 'on')%}
                The back door is open.
                {% endif %}
                It's {{ states("sensor.living_room_climate_sensor") }}°C inside.
            style:
              .: |
                ha-card {
                  margin-top: -15px;
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 15px;
                    font-weight: thin;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
      - type: horizontal-stack
        cards:
            # #################################
            # Icon to display - First button
            # #################################
          - type: 'custom:button-card'
            icon: 'mdi:lightbulb-multiple'
            show_icon: true
            show_name: false
            style: |
              ha-card {
                margin: 10px;
                box-shadow:
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.9),8px 8px 8px 0 rgba(0,0,0,.1);
                  {% elif is_state('sun.sun', 'below_horizon') %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.2);
                  {% endif %}
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace/lights
            styles:
              card:
                - width: 80px
                - height: 80px
                - border-radius: 15px
                - background-color: var(--primary-background-color)
              icon:
                - color: var(--primary-text-color)
          - type: vertical-stack
            cards:
            # #################################
            # Big text to display - First button
            # #################################
              - type: markdown
                content: |
                    # Devices
                style:
                  .: |
                    ha-card {
                      margin-top: 15px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      height: 20px;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
            # #################################
            # Small text to display - First button
            # #################################
              - type: markdown
                content: >
                  # There are {{expand(states.group.bedroom_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length + expand(states.group.office_devices) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length + expand(states.group.downstairs_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length }} devices on
                style:
                  .: |
                    ha-card {
                      margin-top: -35px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
      - type: horizontal-stack
        cards:
            # #################################
            # Icon to display - Second button
            # #################################
          - type: 'custom:button-card'
            icon: 'mdi:baby'
            show_icon: true
            show_name: false
            style: |
              ha-card {
                margin: 10px;
                box-shadow:
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.9),8px 8px 8px 0 rgba(0,0,0,.1);
                  {% elif is_state('sun.sun', 'below_horizon') %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.2);
                  {% endif %}
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace/nursery
            styles:
              card:
                - width: 80px
                - height: 80px
                - border-radius: 15px
                - background-color: var(--primary-background-color)
              icon:
                - color: var(--primary-text-color)
          - type: vertical-stack
            cards:
            # #################################
            # Big text to display - Second button
            # #################################
              - type: markdown
                content: |
                    # Suzanne
                style:
                  .: |
                    ha-card {
                      margin-top: 15px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      height: 20px;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
            # #################################
            # Small text to display - Second button
            # #################################
              - type: markdown
                content: >
                  # It's {{ states("sensor.bedroom_climate_sensor") }}°C in the baby room
                style:
                  .: |
                    ha-card {
                      margin-top: -35px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
            # #################################
            # Big text to display - Third button
            # #################################
              - type: markdown
                content: |
                  # Robert Roborock
                style:
                  .: |
                    ha-card {
                      margin-top: 15px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      height: 20px;
                      text-align: right;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
            # #################################
            # Small text to display - Third button
            # #################################
              - type: markdown
                content: >
                  {% if is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning')%} # Cleaning right now
                  {% elif is_state('vacuum.xiaomi_vacuum_cleaner', 'returning')%} # Returning to dock
                  {% else %}
                  {% set up_time = as_timestamp(now()) - as_timestamp(state_attr('vacuum.xiaomi_vacuum_cleaner' , 'clean_stop')) %}
                  {% set days = (up_time // (60 * 60 * 24)) | int %}
                  {% set weeks = (days // 7) | int %}
                  {% set hours = (up_time // (60 * 60)) | int %}
                  {% set hours =  hours - days * 24 %}{% set minutes = (up_time // 60) | int %}
                  {% set minutes = minutes - (days * 24 * 60) - (hours * 60) %}
                  {% set days = (days | int) - (weeks * 7) %}
                  {% macro phrase(value, name) %}
                  {%- set value = value | int %}
                  {%- set end = 's' if value > 1 else '' %}
                  {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
                  {%- endmacro %}
                  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'),
                   phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
                  {% set last_comma = text.rfind(',') %}
                  {%- set text = text[:last_comma] + ' and ' + text[last_comma + 1:] if last_comma > 0 else text%}
                  # Last vacuumed {{ text }} ago
                  {% endif %}
                style:
                  .: |
                    ha-card {
                      margin-top: -35px;
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      text-align: right;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
            # #################################
            # Icon to display - third button
            # #################################
          - type: 'custom:button-card'
            icon: 'mdi:robot-vacuum'
            show_icon: true
            show_name: false
            style: |
              ha-card {
                margin: 10px;
                box-shadow:
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.9),8px 8px 8px 0 rgba(0,0,0,.1);
                  {% elif is_state('sun.sun', 'below_horizon') %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.2);
                  {% endif %}
              }
            styles:
              card:
                - width: 80px
                - height: 80px
                - border-radius: 15px
                - background-color: var(--primary-background-color)
              icon:
                - color: var(--primary-text-color)
            tap_action:
              action: call-service
              service: script.vacuum_toggle
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
                # Big text to display - First button
              - type: markdown
                content: |
                  # Lights
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      height: 20px;
                      margin-top: 15px;
                      text-align: right;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
# Small text to display - First button
              - type: markdown
                content: >
                  # There are {{expand(states.group.bedroom_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length + expand(states.group.office_devices) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length + expand(states.group.downstairs_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list | length }} lights on
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                      text-align: right;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
            # Icon to display - First button
          - type: 'custom:button-card'
            icon: 'mdi:lightbulb-multiple'
            show_icon: true
            show_name: false
            style: |
              ha-card {
                margin: 10px;
                box-shadow:
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.9),8px 8px 8px 0 rgba(0,0,0,.1);
                  {% elif is_state('sun.sun', 'below_horizon') %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.2);
                  {% endif %}
              }
            styles:
              card:
                - width: 80px
                - height: 80px
                - border-radius: 15px
                - background-color: var(--primary-background-color)
              icon:
                - color: var(--primary-text-color)
            tap_action:
              action: navigate
              navigation_path: /lovelace/lights
