- url: /local/custom_ui/mini-media-player/mini-media-player-bundle.js?v=0.9.8
  type: module
- url: https://unpkg.com/moment@2.22.2/moment.js
  type: js
- url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
  type: module
- url: /local/custom_ui/xiaomi-vacuum-card/xiaomi-vacuum-card.js?v=2.2.1
  type: js
- url: /local/custom_ui/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
  type: module
- url: /local/custom_ui/mini-graph-card/mini-graph-card-bundle.js?v=0.6.0
  type: module
- url: /local/custom_ui/weather-card-chart/weather-card-chart.js
  type: module
- url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
  type: module
- url: /local/custom_ui/air-visual-card/air-visual-card.js
  type: js
- url: /local/custom_ui/tiles-card/tiles-card.js?v=0.1
  type: js
- url: https://cdn.jsdelivr.net/npm/rgb-light-card
  type: js
- url: /local/custom_ui/slider-entity-row/slider-entity-row.js
  type: module
- url: /local/custom_ui/layout-card/layout-card.js
  type: module
- url: /local/custom_ui/button-card/button-card.js?v=3.3.6
  type: module
- url: /local/custom_ui/fold-entity-row/fold-entity-row.js
  type: module
- url: /local/custom_ui/time-picker-card/time-picker-card.js
  type: module
- url: /local/custom_ui/card-mod/card-mod.js?v=0.0.1
  type: module
- url: /local/custom_ui/custom-header/custom-header.js?v=0.0.1
  type: module
- url: /local/custom_ui/swipe-card/swipe-card.js
  type: module
