- id: alarm
  alias: "Alarm"
  description: "Activate lights and radio starting 10 minutes before alarm time"
  trigger:
    - platform: template
      value_template: "{% set stamp = state_attr('input_datetime.alarm_pieter', 'timestamp') | int %}{% set triggertime = (stamp - 600) | timestamp_custom('%H:%M', False)%}{% if triggertime == states('sensor.time') %}true{%endif%}"
  action:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Monday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_monday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Tuesday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_tuesday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Wednesday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_wednesday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Thursday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_thursday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Friday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_friday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Saturday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_saturday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
      - conditions:
        - condition: template
          value_template: "{{ now().strftime('%A') == 'Sunday' }}"
        - condition: template
          value_template: "{{ states('input_boolean.alarm_sunday') == 'on'}}"
        sequence:
          service: script.wake_up_sequence
