- id: motion_hallway
  alias: "Motion Hallway"
  description: "Turn on light when there is motion in the hallway"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_downstairs
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_sensor_upstairs
      to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.led_controller
    - choose:
        - conditions:
          - condition:
            condition: or
            conditions:
              - condition: sun
                after: sunset
              - condition: sun
                before: sunrise
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.lidl_led_1
                rgb_color: [255,150,50]
                brightness: 150
            - service: light.turn_on
              data:
                entity_id: light.hall_light
                kelvin: 1750
                brightness: 5
      default:
        - service: light.turn_on
          data:
            entity_id: light.hall_light
            kelvin: 3000
            brightness: 100
    - wait_template: " {{ is_state('group.motion_hallway', 'off') }} "
    - service: light.turn_off
      entity_id: light.hall_light
    - service: switch.turn_off
      entity_id: switch.led_controller
      # wait two and a half minute before turning off cloud leds as well
    - delay: '00:02:30'
    - service: light.turn_off
      entity_id: light.lidl_led_1
- id: motion_stairway
  alias: "Motion Stairway"
  description: "Turn on light when there is motion in the stairway"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_office
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_sensor_stairs
      to: "on"
  action:
    - choose:
        - conditions:
          - condition: time
            after: '21:00:00'
            before: '07:00:00'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.stair_light
                kelvin: 1750
                brightness: 5
      default:
        - service: light.turn_on
          data:
            entity_id: light.stair_light
            kelvin: 3000
            brightness: 100
    - wait_template: " {{ is_state('group.motion_stairway', 'off') }} "
    - service: light.turn_off
      entity_id: light.stair_light
