- id: theme_toggle_day
  alias: Theme toggle day
  description: Toggle theme during dusk
  trigger:
  - event: sunrise
    platform: sun
  action:
    - service: frontend.set_theme
      data:
        name: clear
- id: theme_toggle_night
  alias: Theme toggle night
  description: Toggle theme during dawn
  trigger:
  - event: sunset
    platform: sun
  action:
    - service: frontend.set_theme
      data:
        name: slate
