bedroom_lights:
  name: Bedroom Lights
  entities:
    - light.bedroom_ceiling_light
    - light.reading_light
    - light.bedlight
living_room_lights:
  name: Living Room Lights
  entities:
    - light.bar_lamp
    - light.corner_lamp
    - light.tower_lamp
    - light.led_strip_2
    - switch.christmas_tree
downstairs_lights:
  name: Downstairs Lights
  entities:
    - light.bar_lamp
    - light.corner_lamp
    - light.tower_lamp
    - light.led_strip_2
    - light.ivar_lamp
    - switch.christmas_tree
people:
  name: People
  entities:
    - device_tracker.pieter
    - device_tracker.sarah
expect_arrival:
  name: Expect someone arriving home
  entities:
    - input_boolean.expect_device_tracker_arrival_pieter
    - input_boolean.expect_device_tracker_arrival_sarah
motion_hallway:
  name: Motion Hallway
  entities:
    - binary_sensor.motion_sensor_upstairs
    - binary_sensor.motion_sensor_downstairs
motion_stairway:
  name: Motion Stairway
  entities:
    - binary_sensor.motion_sensor_office
    - binary_sensor.motion_sensor_stairs
office_devices:
  name: Office Devices
  entities:
    - switch.star_light
    - switch.desk
    - switch.second_desk
    - light.led_strip
    - light.red_lamp
office_lights:
  name: Office Lights
  entities:
    - switch.star_light
    - light.led_strip
    - light.red_lamp

