title: Tatooine
# background: content-box radial-gradient(grey, black)
views:
  - title: Home
    path: downstairs
    icon: mdi:home
    cards:
          - type: horizontal-stack
            cards:
              - type: markdown
                content: |
                  # {{states('sensor.time')}}
                  {{states('sensor.date')}}
              - type: markdown
                content: |
                  ## <ha-icon icon="mdi:thermometer"></ha-icon> {{states('sensor.living_room_climate_sensor')}} °C
                  ## <ha-icon icon="mdi:water-percent"></ha-icon> {{states('sensor.living_room_climate_sensor_2')}} %
          - type: custom:weather-card
            entity: weather.dark_sky
          - type: custom:tiles-card
            card_settings:
              columns: 2
            global_settings:
              label_sec:
                color:
                  value: white
                padding: 10px
              background:
                value_on: var(--primary-color)
                value_off: var(--medium-grey-color)
            entities:
              - entity: group.downstairs_lights
                label_sec:
                  value: All Downstairs Lights
              - entity: group.bedroom_lights
                label_sec:
                  value: All Bedroom Lights
          - type: custom:tiles-card
            card_settings:
              columns: 4
            global_settings:
              label_sec:
                color:
                  value: white
                padding: 5px
              icon:
                color:
                  value: white
                value_on: mdi:lightbulb-on
                value_off: mdi:lightbulb
                size: 35px
              background:
                value_on: var(--primary-color)
                value_off: var(--medium-grey-color)
            entities:
              - entity: light.bar_lamp
                label_sec:
                  value: Bar Lamp
              - entity: light.corner_lamp
                label_sec:
                  value: Corner Lamp
              - entity: light.tower_lamp
                label_sec:
                  value: Tower Lamp
              - entity: light.garden_lights
                label_sec:
                  value: Garden Lights
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.led_strip_2
                toggle: true
              - type: 'custom:rgb-light-card'
                entity: light.led_strip_2
                justify: around
                colors:
                  #rgb values between 0 and 255
                  #brightnees between 0 and 255
                    - rgb_color:
                          - 254
                          - 255
                          - 0
                    - rgb_color:
                          - 255
                          - 129
                          - 1
                    - rgb_color:
                          - 255
                          - 6
                          - 128
                    - rgb_color:
                          - 70
                          - 6
                          - 255
                    - rgb_color:
                          - 0
                          - 255
                          - 126
          - type: custom:tiles-card
            card_settings:
              columns: 2
            global_settings:
              label:
                padding: 3px
                color:
                  value: white
              icon:
                color:
                  value: white
                size: 30px
                padding: 3px
            entities:
              - entity: sensor.washer_status
                icon:
                  value: mdi:washing-machine
                templates:
                  label: >-
                    if (entities["sensor.washer_status"].state ==
                    "on") return "Wally is washing"; else return "Wally is idle";
                  background: >-
                    if (entities["sensor.washer_status"].state ==
                    "on") return "var(--primary-color)"; else return "var(--medium-grey-color)";
              - entity: sensor.washer_status
                icon:
                  value: mdi:tumble-dryer
                templates:
                  label: >-
                    if (entities["sensor.washer_status"].state ==
                    "on") return "Drew is drying"; else return "Drew is idle";
                  background: >-
                    if (entities["sensor.washer_status"].state ==
                    "on") return "var(--primary-color)"; else return "var(--medium-grey-color)";
          - type: custom:tiles-card
            card_settings:
              columns: 3
            global_settings:
              label_sec:
                color:
                  value: white
                padding: 5px
              icon:
                color:
                  value: white
                value_on: mdi:lightbulb-on
                value_off: mdi:lightbulb
                size: 35px
              background:
                value_on: var(--primary-color)
                value_off: var(--medium-grey-color)
            entities:
              - entity: light.bedlight
                label_sec:
                  value: Bedlight
              - entity: light.reading_light
                label_sec:
                  value: Reading Light
              - entity: light.bedroom_ceiling_light
                label_sec:
                  value: Bedroom Ceiling
              - entity: light.hall_light
                label_sec:
                  value: Hall Light
              - entity: switch.led_controller
                label_sec:
                  value: Bathroom LEDs
              - entity: switch.star_light
                label_sec: Star Light
          - type: custom:tiles-card
            card_settings:
              columns: 2
            global_settings:
              label_sec:
                color:
                  value: white
                padding: 10px
              background:
                value_on: var(--primary-color)
                value_off: var(--medium-grey-color)
            entities:
              - entity: switch.desk
                label_sec:
                  value: Desk
              - entity: switch.desk_2
                label_sec:
                  value: Second Desk
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.led_strip
                toggle: true
              - type: 'custom:rgb-light-card'
                entity: light.led_strip
                justify: around
                colors:
                  #rgb values between 0 and 255
                    - rgb_color:
                          - 254
                          - 255
                          - 0
                    - rgb_color:
                          - 255
                          - 129
                          - 1
                    - rgb_color:
                          - 255
                          - 6
                          - 128
                    - rgb_color:
                          - 70
                          - 6
                          - 255
                    - rgb_color:
                          - 0
                          - 255
                          - 126
  - title: Climate
    path: climate
    icon: mdi:thermometer-low
    cards:
      - type: custom:mini-graph-card
        name: WIND SPEED
        entities:
          - entity: sensor.dark_sky_wind_speed
        color_thresholds:
          - value: 1
            color: "#00FF2E"
          - value: 12
            color: "#0080ff"
          - value: 30
            color: "#7f00ff"
          - value: 60
            color: "#ff0000"
        show:
          fill: false
        hour24: true
        hours_to_show: 72
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            name: TEMPERATURE INSIDE
            entities:
              - entity: sensor.bedroom_climate_sensor
                name: Bedroom
              - entity: sensor.living_room_climate_sensor_2
                name: Living Room
              - entity: sensor.office_climate_sensor_2
                name: Office
              - entity: sensor.nighttime
                color: gray
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
            show:
              labels: true
            hour24: true
            hours_to_show: 72
          - type: custom:mini-graph-card
            name: TEMPERATURE OUTSIDE
            entities:
              - entity: sensor.dark_sky_temperature
              - entity: sensor.nighttime
                color: gray
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
            hour24: true
            hours_to_show: 72
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            name: HUMIDITY INSIDE
            entities:
              - entity: sensor.bedroom_climate_sensor_2
                name: Bedroom
              - entity: sensor.living_room_climate_sensor
                name: Living Room
              - entity: sensor.office_climate_sensor
                name: Office
              - entity: sensor.nighttime
                color: gray
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
            show:
              labels: true
            hour24: true
            hours_to_show: 72
          - type: custom:mini-graph-card
            name: HUMIDITY OUTSIDE
            icon: mdi:water-percent
            entities:
              - entity: sensor.dark_sky_humidity
              - entity: sensor.nighttime
                color: gray
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
            hour24: true
            hours_to_show: 72
      - type: custom:air-visual-card
        air_pollution_level: sensor.u_s_air_pollution_level
        air_quality_index: sensor.u_s_air_quality_index
        main_pollutant: sensor.u_s_main_pollutant
        temp: weather.dark_sky
        city: 'Brugge'
      - type: iframe
        url: https://gadgets.buienradar.nl/gadget/zoommap/?lat=51.15432&lng=3.23128&overname=2&zoom=8&naam=Oostkamp&size=3&voor=1
        aspect_ratio: 113%
  - title: Security
    path: security
    icon: mdi:cctv
    cards:
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
          - binary_sensor.back_door_sensor
          - sensor.back_door_last_opened
          - binary_sensor.front_door_sensor
          - sensor.front_door_last_opened
      - type: picture-entity
        entity: camera.patio
        camera_view: live
      - type: entities
        show_header_toggle: false
        entities:
          - input_boolean.guest_mode
  - title: Automations
    path: automations
    icon: mdi:home-assistant
    cards:
      - type: picture-entity
        entity:  sensor.pieter_presence
        image: /local/lovelace/photos/picture1.jpg
      - type: picture-entity
        entity:  sensor.sarah_presence
        image: /local/lovelace/photos/picture2.jpg
      - type: entities
        title: Vacuum automation
        show_header_toggle: true
        entities:
          - entity: input_boolean.automate_vacuum_weekdays
            name: Automate on weekdays
          - entity: input_datetime.vacuum_time_weekday
            name: Start at
          - entity: input_boolean.automate_vacuum_weekends
            name: Automate on weekends
          - entity: input_datetime.vacuum_time_weekend
            name: Start at
      - type: vertical-stack
        cards:
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.xiaomi_vacuum_cleaner
            image: false
            name: Vacuum
            buttons: true
  - title: Brix
    path: brix
    icon: mdi:desktop-classic
    cards:
      - type: entities
        title: Docker Containers
        show_header_toggle: false
        entities:
          - sensor.docker_hass
          - sensor.docker_ha_dockermon
          - sensor.docker_deconz
          - sensor.docker_nodered
          - sensor.docker_pihole
      - type: gauge
        entity: sensor.processor_use
        name: CPU
        severity:
          green: 0
          yellow: 45
          red: 85
      - type: gauge
        entity: sensor.memory_use_percent
        name: Memory
        severity:
          green: 0
          yellow: 45
          red: 85
      - type: gauge
        entity: sensor.disk_use_percent
        name: Disk
        severity:
          green: 0
          yellow: 45
          red: 85
      - type: custom:mini-graph-card
        name: RESOURCES
        show:
         state: false
        entities:
          - entity: sensor.processor_use
            name: CPU Use
          - entity: sensor.memory_use_percent
            name: Memory Use
          - entity: sensor.disk_use_percent
            name: Disk use
      - type: custom:mini-graph-card
        name: NETWORK
        show:
         state: false
        entities:
          - sensor.network_throughput_in_enp2s0
          - sensor.network_throughput_out_enp2s0
  - title: Testing Zone
    path: testing
    icon: mdi:test-tube
    cards:
      - type: entities
        title: Testing alarms
        show_header_toggle: false
        entities:
          - input_boolean.alarm_pieter_weekend
          - input_boolean.alarm_pieter_weekday
          - input_datetime.alarm_pieter
          - input_boolean.alarm_pieter_lights
          - input_boolean.alarm_pieter_radio
      - type: custom:mini-graph-card
        name: DRYER POWER
        entities:
          - entity: sensor.dryer_power
        color_thresholds:
          - value: 1
            color: "#00FF2E"
          - value: 500
            color: "#0080ff"
          - value: 1000
            color: "#7f00ff"
          - value: 1200
            color: "#ff0000"
        show:
          fill: false
        hour24: true
        hours_to_show: 72
      - type: custom:mini-graph-card
        name: ILLUMINANCE
        entities:
          - entity: sensor.illuminance
        show:
          fill: false
        hour24: true
        hours_to_show: 24
