# Non Binary Presence Detection switches this on and off, it is used for light automations
expect_device_tracker_arrival_pieter:
  initial: off
expect_device_tracker_arrival_sarah:
  initial: off

# To enable/disable automatic vacuuming
sarah_worked_night_shift:
  initial: off
automate_vacuum_monday:
  initial: on
automate_vacuum_tuesday:
  initial: on
automate_vacuum_wednesday:
  initial: on
automate_vacuum_thursday:
  initial: on
automate_vacuum_friday:
  initial: on
automate_vacuum_saturday:
  initial: on
automate_vacuum_sunday:
  initial: on

vacuumed_today:
  initial: off
cleaned_before_docking:
  initial: off

# Alarms
alarm_lights:
  initial: on
alarm_radio:
  initial: on
alarm_monday:
  initial: on
alarm_tuesday:
  initial: on
alarm_wednesday:
  initial: on
alarm_thursday:
  initial: on
alarm_friday:
  initial: on
alarm_saturday:
  initial: on
alarm_sunday:
  initial: on

# For beta testing automations and to disable/enable some automations
guest_mode:
  name: Guest Mode
  initial: off

doorbell_lights_in_progress:
  initial: off
baby_monitor:
  initial: off
