title: Downstairs
path: downstairs
panel: true
cards:
  # Better layout control
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: markdown
        content: |
          # {{states('sensor.time')}}
          {{states('sensor.date')}}
      - type: custom:weather-card
        entity: weather.dark_sky
        #- type: markdown
        #   content: |
        #     ## <ha-icon icon="mdi:thermometer"></ha-icon> {{states('sensor.living_room_climate_sensor_2')}} °C
        #     ## <ha-icon icon="mdi:water-percent"></ha-icon> {{states('sensor.living_room_climate_sensor')}} %
      - break
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: Downstairs Lights
            entity: group.downstairs_lights
            show_icon: false
            color_type: card
            color: var(--primary-color)
            styles:
              name:
                - font-size: 15px
                - padding: 1px
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
          - type: custom:button-card
            name: Bedroom Lights
            entity: group.bedroom_lights
            show_icon: false
            color_type: card
            color: var(--primary-color)
            styles:
              name:
                - font-size: 15px
                - padding: 1px
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: Bar Lamp
            entity: light.bar_lamp
            color_type: card
            color: var(--primary-color)
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
          - type: custom:button-card
            name: Corner Lamp
            entity: light.corner_lamp
            color_type: card
            color: var(--primary-color)
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
          - type: custom:button-card
            name: Tower Lamp
            entity: light.tower_lamp
            color_type: card
            color: var(--primary-color)
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
          - type: custom:button-card
            name: Garden Lights
            entity: light.garden_lights
            color_type: card
            color: var(--primary-color)
            styles:
              name:
                - font-size: 15px
                - padding: 1px
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.led_strip_2
            toggle: true
          - type: 'custom:rgb-light-card'
            entity: light.led_strip_2
            justify: around
            colors:
              #rgb values between 0 and 255
              #brightnees between 0 and 255
                - rgb_color:
                      - 254
                      - 255
                      - 0
                - rgb_color:
                      - 255
                      - 129
                      - 1
                - rgb_color:
                      - 255
                      - 6
                      - 128
                - rgb_color:
                      - 70
                      - 6
                      - 255
                - rgb_color:
                      - 0
                      - 255
                      - 126
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: >
                 [[[
                   if (entity.state == 'on')
                     return "Wally is washing";
                   else
                     return "Wally is idle";
                 ]]]
            icon: mdi:washing-machine
            entity: sensor.washer_status
            color_type: card
            color: var(--primary-color)
            styles:
              card:
                - height: 80px
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
          - type: custom:button-card
            name: >
                 [[[
                   if (entity.state == 'on')
                     return "Drew is drying";
                   else
                     return "Drew is idle";
                 ]]]
            icon: mdi:tumble-dryer
            entity: sensor.dryer_status
            color_type: card
            color: var(--primary-color)
            styles:
              card:
                - height: 80px
            state:
              - value: "off"
                color: var(--medium-grey-color)
                styles:
                  name:
                    - color: var(--disabled-text-color)
                  icon:
                    - color: var(--disabled-text-color)
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        image: false
        name: Robert Roborock Vacuum
        labels: false
        buttons: true
      - break
      - type: custom:mini-graph-card
        name: TEMPERATURE INSIDE
        entities:
          - entity: sensor.bedroom_climate_sensor
            name: Bedroom
          - entity: sensor.living_room_climate_sensor_2
            name: Living Room
          - entity: sensor.office_climate_sensor_2
            name: Office
          - entity: sensor.nighttime
            color: gray
            name: Night
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        show:
          labels: true
        hour24: true
        hours_to_show: 72
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            name: HUMIDITY INSIDE
            entities:
              - entity: sensor.bedroom_climate_sensor_2
                name: Bedroom
              - entity: sensor.living_room_climate_sensor
                name: Living Room
              - entity: sensor.office_climate_sensor
                name: Office
              - entity: sensor.nighttime
                color: gray
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
            show:
              labels: true
            hour24: true
            hours_to_show: 72
