baseURL = "https://blog.plab.be/"
languageCode = "en-us"
title = "Pieter's Lab"
theme = "hyde"

[params]
  themeColor = "theme-base-09"
  description = "To keep family, friends, and anyone else who is interested, up to date with my newest ventures"
