version: '3.1'
networks:
  traefik2_proxy:
    external:
      name: traefik2_proxy
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    pid: host
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik2_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
      - "61209:61209"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.glances-rtr.entrypoints=https"
      - "traefik.http.routers.glances-rtr.rule=Host(`glances.$DOMAINNAME`)"
      - "traefik.http.routers.glances-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.glances-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.glances-rtr.service=glances-svc"
      - "traefik.http.services.glances-svc.loadbalancer.server.port=61208"
