conditional_notify_mobiles:
  mode: single
  alias: "notify mobiles if guest_mode not enabled"
  sequence:
    - condition: state
      entity_id: 'input_boolean.guest_mode'
      state: 'off'
    - service: notify.mobiles
      data_template:
        message: "{{ message }}"
        title: "{{title}}"
        data:
          tag: "{{tag}}"
send_test_notification:
  mode: single
  alias: "notify mobiles if guest_mode not enabled"
  sequence:
    - service: notify.mobiles
      data_template:
        message: "Testing notify.mobiles"
        title: "Test"
        data:
          tag: "test"
