wake_up_sequence:
  sequence:
    - service: script.gradually_turn_on_bedroom_ceiling_light
    - delay:
        minutes: 10
    - service: script.start_radio_bedroom
    - service: script.turn_on_bedroom_lights
turn_on_bedroom_lights:
  sequence:
    - condition: template
      value_template: "{{ states('input_boolean.alarm_lights') == 'on'}}"
    - service: light.turn_on
      data:
        entity_id: light.bedlight
    - service: light.turn_on
      data:
        entity_id: light.reading_light
        rgb_color: [255,63,0]
        brightness: 145
start_radio_bedroom:
  sequence:
    - condition: template
      value_template: "{{ states('input_boolean.alarm_radio') == 'on'}}"
    - service: media_player.play_media
      data:
        entity_id: "media_player.bedroom_speaker"
        media_content_id: "http://icecast.vrtcdn.be/radio1-high.mp3"
        media_content_type: "music"
gradually_turn_on_bedroom_ceiling_light:
  sequence:
    - condition: template
      value_template: "{{ states('input_boolean.alarm_lights') == 'on'}}"
    - service: light.turn_on
      data:
        entity_id: light.bedroom_ceiling_light
        brightness: 1
    - alias: Gradually turn on a light
      repeat:
        while:
          - condition: template
            value_template: "{{ (state_attr('light.bedroom_ceiling_light', 'brightness')|int) < 120 }}"
        sequence:
          - delay:
              seconds: 5
          - service: light.turn_on
            data_template:
              entity_id: light.bedroom_ceiling_light
              brightness: "{{ states.light.bedroom_ceiling_light.attributes.brightness | int + 1 }}"
